[package]
name = "amber_transpile"
version = "1.16.0"
edition = "2021"
authors = ["Henry Zhang"]
description = "Fast TypeScript transpile and bundling engine for Amber runtime"
license = "MIT"
readme = "README.md"
repository = "https://github.com/zh30/amberjs"
homepage = "https://amberjs.com"
documentation = "https://docs.rs/amber_transpile"
keywords = ["javascript", "typescript", "transpile"]
categories = ["development-tools"]

[dependencies]
oxc = { version = "0.147", default-features = false, features = [
    "semantic",
    "transformer",
    "codegen",
] }
anyhow = "1.0"
base64 = "0.23"
sha2 = "0.10"
once_cell = "1.0"
regex = "1.0"
serde_json = "1.0"
